# Generated by Django 4.1.6 on 2023-02-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('percent_off', models.IntegerField()),
                ('duration', models.CharField(choices=[('once', 'Once'), ('forever', 'Forever'), ('repeating', 'Repeating')], default='once', max_length=25)),
                ('created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('currency', models.CharField(choices=[('rub', 'Rub'), ('usd', 'Usd')], default='rub', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tax', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('display_name', models.CharField(choices=[('Sales Tax', 'Sales Tax'), ('VAT', 'Vat'), ('GST', 'Gst')], default='Sales Tax', max_length=12)),
                ('inclusive', models.BooleanField(default=False)),
                ('percentage', models.FloatField()),
                ('created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strip.discount')),
                ('items', models.ManyToManyField(to='strip.item')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strip.tax')),
            ],
        ),
    ]
